export const ADD_EVENT = 'ADD_EVENT'
export const EDIT_EVENT = 'EDIT_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'
export const PREV_DAY = 'PREV_DAY'
export const NEXT_DAY = 'NEXT_DAY'
export const TODAY = 'TODAY'